// Generated by GenerateShaderCommonProbe.py, do not edit by hand. The probe has no shader stage
// of its own: it exists so that CheckShaderProperties.py can compile both generated headers and
// compare the layouts, the bindings and the framebuffer declarations that glslc and dxc derive
// from them. Every framebuffer is touched, because dxc drops the unused declarations and the
// checker can only compare the ones inside a function.

#define DESC_SET_FRAMEBUFFERS 0
#define DESC_SET_GLOBAL_UNIFORM 1

#include "ShaderCommonHLSL.hlsli"

#define PROBE_DESC_SET 2

struct Push_BT
{
    ShVertPreprocessing push;
};

// A fixed size array needs an explicit wrapper, because a block that contains an array is not
// unwrapped by the checker, while a block that contains a single struct is.
struct ProbeShPortalInstance_BT
{
    ShPortalInstance portals[PORTAL_MAX_COUNT];
};

[[vk::push_constant]] ConstantBuffer<Push_BT> pushConstant;

[[vk::binding(0, PROBE_DESC_SET)]] StructuredBuffer<ShVertex>                           vertices;
[[vk::binding(1, PROBE_DESC_SET)]] StructuredBuffer<ShGeometryInstance>                 geometryInstances;
[[vk::binding(2, PROBE_DESC_SET)]] StructuredBuffer<ShTonemapping>                      tonemapping;
[[vk::binding(3, PROBE_DESC_SET)]] StructuredBuffer<ShLightEncoded>                     lights;
[[vk::binding(4, PROBE_DESC_SET)]] StructuredBuffer<ShIndirectDrawCommand>              drawCmds;
[[vk::binding(5, PROBE_DESC_SET)]] StructuredBuffer<ShLensFlareInstance>                lensFlares;
[[vk::binding(6, PROBE_DESC_SET)]] StructuredBuffer<ShDecalInstance>                    decals;
[[vk::binding(7, PROBE_DESC_SET)]] ConstantBuffer<ProbeShPortalInstance_BT> portalBuffer;
[[vk::binding(8, PROBE_DESC_SET)]] RWStructuredBuffer<float> probeOutput;

[numthreads(1, 1, 1)]
void main(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    float v = 0.0;

    uint2 pix = uint2(0, 0);
    float2 uv = float2(0.5, 0.5);

    // ShGlobalUniform
    v += globalUniform.view[0][0] + globalUniform.invView[0][0] + globalUniform.viewPrev[0][0] +
         globalUniform.projection[0][0] + globalUniform.invProjection[0][0] +
         globalUniform.projectionPrev[0][0] + globalUniform.volumeViewProj[0][0] +
         globalUniform.volumeViewProjInv[0][0] + globalUniform.volumeViewProj_Prev[0][0] +
         globalUniform.volumeViewProjInv_Prev[0][0] + globalUniform.cellWorldSize +
         globalUniform.renderWidth + float(globalUniform.__pad0) + float(globalUniform.__pad1) +
         globalUniform.renderHeight + float(globalUniform.frameId) + globalUniform.timeDelta +
         globalUniform.minLogLuminance + globalUniform.maxLogLuminance + globalUniform.luminanceWhitePoint +
         float(globalUniform.stopEyeAdaptation) + float(globalUniform.directionalLightExists) +
         globalUniform.polyLightSpotlightFactor + float(globalUniform.skyType) +
         globalUniform.skyColorMultiplier + float(globalUniform.skyCubemapIndex) +
         globalUniform.skyColorDefault.x + globalUniform.cameraPosition.x +
         globalUniform.cameraPositionPrev.x + float(globalUniform.debugShowFlags) +
         float(globalUniform.indirSecondBounce) + float(globalUniform.lightCount) +
         float(globalUniform.lightCountPrev) + globalUniform.emissionMapBoost +
         globalUniform.emissionMaxScreenColor + globalUniform.normalMapStrength +
         globalUniform.skyColorSaturation + globalUniform.emissionSharpMask +
         globalUniform.talSelfLitOffset + float(globalUniform.emissionBlendMode) +
         globalUniform.emissionBlendStrength + globalUniform.skyAmbientLod + globalUniform.rayLength +
         float(globalUniform.rayCullBackFaces) + float(globalUniform.rayCullMaskWorld) +
         globalUniform.bloomIntensity + globalUniform.bloomThreshold +
         globalUniform.bloomEmissionMultiplier + float(globalUniform.reflectRefractMaxDepth) +
         float(globalUniform.cameraMediaType) + globalUniform.indexOfRefractionWater +
         globalUniform.indexOfRefractionGlass + globalUniform.waterTextureDerivativesMultiplier +
         float(globalUniform.volumeEnableType) + globalUniform.volumeScattering +
         float(globalUniform.forceNoWaterRefraction) + float(globalUniform.waterNormalTextureIndex) +
         float(globalUniform.noBackfaceReflForNoMediaChange) + globalUniform.time +
         globalUniform.waterWaveSpeed + globalUniform.waterWaveStrength +
         globalUniform.waterColorAndDensity.x + globalUniform.acidColorAndDensity.x +
         globalUniform.cameraRayConeSpreadAngle + globalUniform.waterTextureAreaScale +
         float(globalUniform.squareInputRoughness) + globalUniform.upscaledRenderWidth +
         globalUniform.worldUpVector.x + globalUniform.upscaledRenderHeight + globalUniform.jitterX +
         globalUniform.jitterY + globalUniform.primaryRayMinDist +
         float(globalUniform.rayCullMaskWorld_Shadow) + float(globalUniform.lensFlareCullingInputCount) +
         float(globalUniform.applyViewProjToLensFlares) + float(globalUniform.twirlPortalNormal) +
         float(globalUniform.lightIndexIgnoreFPVShadows) + globalUniform.gradientMultDiffuse +
         globalUniform.gradientMultIndirect + globalUniform.gradientMultSpecular +
         globalUniform.minRoughness + globalUniform.volumeCameraNear + globalUniform.volumeCameraFar +
         float(globalUniform.antiFireflyEnabled) + globalUniform.volumeAmbient.x +
         globalUniform.volumeSourceColor.x + globalUniform.volumeDirToSource.x +
         globalUniform.volumeSourceAsymmetry + float(globalUniform.coreQ2RTX) +
         float(globalUniform.q2DepthGradMode) + globalUniform.skyNee +
         float(globalUniform.q2LightStatsMode) + float(globalUniform.reflRefrEarlyOut) +
         float(globalUniform.neeLightSamples) + globalUniform.turbWarpStrength +
         float(globalUniform.instanceGeomInfoOffset[0].x) +
         float(globalUniform.instanceGeomInfoOffsetPrev[0].x) + float(globalUniform.instanceGeomCount[0].x) +
         globalUniform.viewProjCubemap[0][0][0] + globalUniform.skyCubemapRotationTransform[0][0] +
         globalUniform.fogMins[0].x + float(globalUniform.fogIsActive[0]) + globalUniform.fogMaxs[0].x +
         globalUniform.fogColor[0].x + globalUniform.fogDensity[0].x + globalUniform.lightStyleScales[0].x +
         globalUniform.giBounceRays.x + globalUniform.fltEnable.x + globalUniform.fixedAlbedo.x +
         globalUniform.sunBounce.x + globalUniform.levelFogColorDensity.x + globalUniform.levelFogSkyBlend.x;

    // ShVertPreprocessing
    v += float(pushConstant.push.tlasInstanceCount) + float(pushConstant.push.tlasInstanceIsDynamicBits[0]);

    // ShVertex
    v += vertices[0].position.x + vertices[0].normal.x + vertices[0].texCoord.x +
         vertices[0].texCoordLayer1.x + vertices[0].texCoordLayer2.x + float(vertices[0].packedColor) +
         float(vertices[0].cluster) + float(vertices[0].lightStyles) + float(vertices[0].__pad0) +
         float(vertices[0].__pad1) + float(vertices[0].__pad2);

    // ShGeometryInstance
    v += geometryInstances[0].model[0][0] + geometryInstances[0].prevModel[0][0] +
         geometryInstances[0].materialColors[0].x + float(geometryInstances[0].materials0A) +
         float(geometryInstances[0].materials0B) + float(geometryInstances[0].materials0C) +
         float(geometryInstances[0].materials1A) + float(geometryInstances[0].materials1B) +
         float(geometryInstances[0].portalIndex) + float(geometryInstances[0].materials2A) +
         float(geometryInstances[0].materials2B) + float(geometryInstances[0]._unused0) +
         float(geometryInstances[0].flags) + float(geometryInstances[0].baseVertexIndex) +
         float(geometryInstances[0].baseIndexIndex) + float(geometryInstances[0].prevBaseVertexIndex) +
         float(geometryInstances[0].prevBaseIndexIndex) + float(geometryInstances[0].vertexCount) +
         float(geometryInstances[0].indexCount) + geometryInstances[0].defaultRoughness +
         geometryInstances[0].defaultMetallicity + geometryInstances[0].defaultEmission +
         float(geometryInstances[0]._unused1);

    // ShTonemapping
    v += tonemapping[0].tmExposureBias + tonemapping[0].tmExposureSpeedDown +
         tonemapping[0].tmExposureSpeedUp + tonemapping[0].tmLowPercentile +
         tonemapping[0].tmHighPercentile + tonemapping[0].tmMinLuminance + tonemapping[0].tmMaxLuminance +
         tonemapping[0].tmNoiseBlend + tonemapping[0].tmNoiseStops + tonemapping[0].tmDynRangeStops +
         tonemapping[0].tmReinhard + tonemapping[0].tmKneeStart + tonemapping[0].tmWhitePoint +
         tonemapping[0].tmSlopeBlurSigma + tonemapping[0].frameTime + float(tonemapping[0].resetCurve) +
         tonemapping[0].kneeW + tonemapping[0].kneeA + tonemapping[0].kneeB +
         float(tonemapping[0].histogram[0]) + tonemapping[0].curve[0] + tonemapping[0].normalized[0] +
         tonemapping[0].adaptedLuminance + tonemapping[0].avgLuminance;

    // ShLightEncoded
    v += lights[0].color.x + float(lights[0].lightType) + lights[0].data_0.x + lights[0].data_1.x +
         lights[0].data_2.x + lights[0].data_3.x + lights[0].data_4.x + lights[0].data_5.x +
         lights[0].data_6.x + lights[0].data_7.x;

    // ShIndirectDrawCommand
    v += float(drawCmds[0].indexCount) + float(drawCmds[0].instanceCount) + float(drawCmds[0].firstIndex) +
         float(drawCmds[0].vertexOffset) + float(drawCmds[0].firstInstance) + drawCmds[0].positionToCheck_X +
         drawCmds[0].positionToCheck_Y + drawCmds[0].positionToCheck_Z;

    // ShLensFlareInstance
    v += float(lensFlares[0].textureIndex);

    // ShDecalInstance
    v += decals[0].transform[0][0] + float(decals[0].textureAlbedoAlpha) +
         float(decals[0].textureRougnessMetallic) + float(decals[0].textureNormals) + float(decals[0].__pad0);

    // ShPortalInstance
    v += portalBuffer.portals[0].inPosition.x + portalBuffer.portals[0].outPosition.x +
         portalBuffer.portals[0].outDirection.x + portalBuffer.portals[0].outUp.x;

    // One slot per framebuffer: its storage image, its sampled view and its sampler.
    // The sampled view is fetched and sampled too. A uint texture can not be sampled,
    // so one float texture samples every sampler of the table in turn.

    // framebufAlbedo  r11f_g11f_b10f
    framebufAlbedo[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufAlbedo[pix].x);
    v += float(framebufAlbedo_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufAlbedo_Sampler, uv, 0.0).x;

    // framebufAlbedo_Prev  r11f_g11f_b10f
    framebufAlbedo_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufAlbedo_Prev[pix].x);
    v += float(framebufAlbedo_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufAlbedo_Prev_Sampler, uv, 0.0).x;

    // framebufIsSky  r8ui
    framebufIsSky[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufIsSky[pix].x);
    v += float(framebufIsSky_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufIsSky_Sampler, uv, 0.0).x;

    // framebufNormal  r32ui
    framebufNormal[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufNormal[pix].x);
    v += float(framebufNormal_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufNormal_Sampler, uv, 0.0).x;

    // framebufNormal_Prev  r32ui
    framebufNormal_Prev[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufNormal_Prev[pix].x);
    v += float(framebufNormal_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufNormal_Prev_Sampler, uv, 0.0).x;

    // framebufNormalGeometry  r32ui
    framebufNormalGeometry[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufNormalGeometry[pix].x);
    v += float(framebufNormalGeometry_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufNormalGeometry_Sampler, uv, 0.0).x;

    // framebufNormalGeometry_Prev  r32ui
    framebufNormalGeometry_Prev[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufNormalGeometry_Prev[pix].x);
    v += float(framebufNormalGeometry_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufNormalGeometry_Prev_Sampler, uv, 0.0).x;

    // framebufMetallicRoughness  rg8
    framebufMetallicRoughness[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufMetallicRoughness[pix].x);
    v += float(framebufMetallicRoughness_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufMetallicRoughness_Sampler, uv, 0.0).x;

    // framebufMetallicRoughness_Prev  rg8
    framebufMetallicRoughness_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufMetallicRoughness_Prev[pix].x);
    v += float(framebufMetallicRoughness_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufMetallicRoughness_Prev_Sampler, uv, 0.0).x;

    // framebufDepthWorld  r16f
    framebufDepthWorld[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufDepthWorld[pix].x);
    v += float(framebufDepthWorld_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufDepthWorld_Sampler, uv, 0.0).x;

    // framebufDepthWorld_Prev  r16f
    framebufDepthWorld_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufDepthWorld_Prev[pix].x);
    v += float(framebufDepthWorld_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufDepthWorld_Prev_Sampler, uv, 0.0).x;

    // framebufDepthGrad  r16f
    framebufDepthGrad[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufDepthGrad[pix].x);
    v += float(framebufDepthGrad_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufDepthGrad_Sampler, uv, 0.0).x;

    // framebufDepthNdc  r32f
    framebufDepthNdc[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufDepthNdc[pix].x);
    v += float(framebufDepthNdc_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufDepthNdc_Sampler, uv, 0.0).x;

    // framebufMotion  rgba16f
    framebufMotion[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufMotion[pix].x);
    v += float(framebufMotion_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufMotion_Sampler, uv, 0.0).x;

    // framebufUnfilteredDirect  r32ui
    framebufUnfilteredDirect[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufUnfilteredDirect[pix].x);
    v += float(framebufUnfilteredDirect_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufUnfilteredDirect_Sampler, uv, 0.0).x;

    // framebufUnfilteredSpecular  r32ui
    framebufUnfilteredSpecular[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufUnfilteredSpecular[pix].x);
    v += float(framebufUnfilteredSpecular_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufUnfilteredSpecular_Sampler, uv, 0.0).x;

    // framebufUnfilteredIndirectSH_R  rgba16f
    framebufUnfilteredIndirectSH_R[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufUnfilteredIndirectSH_R[pix].x);
    v += float(framebufUnfilteredIndirectSH_R_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufUnfilteredIndirectSH_R_Sampler, uv, 0.0).x;

    // framebufUnfilteredIndirectSH_G  rgba16f
    framebufUnfilteredIndirectSH_G[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufUnfilteredIndirectSH_G[pix].x);
    v += float(framebufUnfilteredIndirectSH_G_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufUnfilteredIndirectSH_G_Sampler, uv, 0.0).x;

    // framebufUnfilteredIndirectSH_B  rgba16f
    framebufUnfilteredIndirectSH_B[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufUnfilteredIndirectSH_B[pix].x);
    v += float(framebufUnfilteredIndirectSH_B_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufUnfilteredIndirectSH_B_Sampler, uv, 0.0).x;

    // framebufSurfacePosition  rgba32f
    framebufSurfacePosition[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufSurfacePosition[pix].x);
    v += float(framebufSurfacePosition_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufSurfacePosition_Sampler, uv, 0.0).x;

    // framebufSurfacePosition_Prev  rgba32f
    framebufSurfacePosition_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufSurfacePosition_Prev[pix].x);
    v += float(framebufSurfacePosition_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufSurfacePosition_Prev_Sampler, uv, 0.0).x;

    // framebufVisibilityBuffer  rgba32f
    framebufVisibilityBuffer[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufVisibilityBuffer[pix].x);
    v += float(framebufVisibilityBuffer_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufVisibilityBuffer_Sampler, uv, 0.0).x;

    // framebufVisibilityBuffer_Prev  rgba32f
    framebufVisibilityBuffer_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufVisibilityBuffer_Prev[pix].x);
    v += float(framebufVisibilityBuffer_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufVisibilityBuffer_Prev_Sampler, uv, 0.0).x;

    // framebufViewDirection  rgba16f
    framebufViewDirection[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufViewDirection[pix].x);
    v += float(framebufViewDirection_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufViewDirection_Sampler, uv, 0.0).x;

    // framebufViewDirection_Prev  rgba16f
    framebufViewDirection_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufViewDirection_Prev[pix].x);
    v += float(framebufViewDirection_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufViewDirection_Prev_Sampler, uv, 0.0).x;

    // framebufPrimaryToReflRefr  rgba32ui
    framebufPrimaryToReflRefr[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufPrimaryToReflRefr[pix].x);
    v += float(framebufPrimaryToReflRefr_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufPrimaryToReflRefr_Sampler, uv, 0.0).x;

    // framebufThroughput  rgba16f
    framebufThroughput[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufThroughput[pix].x);
    v += float(framebufThroughput_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufThroughput_Sampler, uv, 0.0).x;

    // framebufPreFinal  r11f_g11f_b10f
    framebufPreFinal[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufPreFinal[pix].x);
    v += float(framebufPreFinal_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufPreFinal_Sampler, uv, 0.0).x;

    // framebufFinal  r11f_g11f_b10f
    framebufFinal[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufFinal[pix].x);
    v += float(framebufFinal_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufFinal_Sampler, uv, 0.0).x;

    // framebufUpscaledPing  r11f_g11f_b10f
    framebufUpscaledPing[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufUpscaledPing[pix].x);
    v += float(framebufUpscaledPing_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufUpscaledPing_Sampler, uv, 0.0).x;

    // framebufUpscaledPong  r11f_g11f_b10f
    framebufUpscaledPong[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufUpscaledPong[pix].x);
    v += float(framebufUpscaledPong_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufUpscaledPong_Sampler, uv, 0.0).x;

    // framebufMotionDlss  rg16f
    framebufMotionDlss[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufMotionDlss[pix].x);
    v += float(framebufMotionDlss_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufMotionDlss_Sampler, uv, 0.0).x;

    // framebufAccumHistoryLength  rgba16f
    framebufAccumHistoryLength[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufAccumHistoryLength[pix].x);
    v += float(framebufAccumHistoryLength_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufAccumHistoryLength_Sampler, uv, 0.0).x;

    // framebufAccumHistoryLength_Prev  rgba16f
    framebufAccumHistoryLength_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufAccumHistoryLength_Prev[pix].x);
    v += float(framebufAccumHistoryLength_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufAccumHistoryLength_Prev_Sampler, uv, 0.0).x;

    // framebufDiffTemporary  r32ui
    framebufDiffTemporary[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufDiffTemporary[pix].x);
    v += float(framebufDiffTemporary_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufDiffTemporary_Sampler, uv, 0.0).x;

    // framebufDiffAccumColor  r32ui
    framebufDiffAccumColor[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufDiffAccumColor[pix].x);
    v += float(framebufDiffAccumColor_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufDiffAccumColor_Sampler, uv, 0.0).x;

    // framebufDiffAccumColor_Prev  r32ui
    framebufDiffAccumColor_Prev[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufDiffAccumColor_Prev[pix].x);
    v += float(framebufDiffAccumColor_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufDiffAccumColor_Prev_Sampler, uv, 0.0).x;

    // framebufDiffAccumMoments  rg16f
    framebufDiffAccumMoments[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufDiffAccumMoments[pix].x);
    v += float(framebufDiffAccumMoments_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufDiffAccumMoments_Sampler, uv, 0.0).x;

    // framebufDiffAccumMoments_Prev  rg16f
    framebufDiffAccumMoments_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufDiffAccumMoments_Prev[pix].x);
    v += float(framebufDiffAccumMoments_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufDiffAccumMoments_Prev_Sampler, uv, 0.0).x;

    // framebufDiffColorHistory  rgba16f
    framebufDiffColorHistory[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufDiffColorHistory[pix].x);
    v += float(framebufDiffColorHistory_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufDiffColorHistory_Sampler, uv, 0.0).x;

    // framebufDiffPingColorAndVariance  rgba16f
    framebufDiffPingColorAndVariance[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufDiffPingColorAndVariance[pix].x);
    v += float(framebufDiffPingColorAndVariance_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufDiffPingColorAndVariance_Sampler, uv, 0.0).x;

    // framebufDiffPongColorAndVariance  rgba16f
    framebufDiffPongColorAndVariance[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufDiffPongColorAndVariance[pix].x);
    v += float(framebufDiffPongColorAndVariance_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufDiffPongColorAndVariance_Sampler, uv, 0.0).x;

    // framebufSpecAccumColor  r32ui
    framebufSpecAccumColor[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufSpecAccumColor[pix].x);
    v += float(framebufSpecAccumColor_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufSpecAccumColor_Sampler, uv, 0.0).x;

    // framebufSpecAccumColor_Prev  r32ui
    framebufSpecAccumColor_Prev[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufSpecAccumColor_Prev[pix].x);
    v += float(framebufSpecAccumColor_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufSpecAccumColor_Prev_Sampler, uv, 0.0).x;

    // framebufSpecPingColor  r32ui
    framebufSpecPingColor[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufSpecPingColor[pix].x);
    v += float(framebufSpecPingColor_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufSpecPingColor_Sampler, uv, 0.0).x;

    // framebufSpecPongColor  r32ui
    framebufSpecPongColor[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufSpecPongColor[pix].x);
    v += float(framebufSpecPongColor_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufSpecPongColor_Sampler, uv, 0.0).x;

    // framebufIndirAccumSH_R  rgba16f
    framebufIndirAccumSH_R[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufIndirAccumSH_R[pix].x);
    v += float(framebufIndirAccumSH_R_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufIndirAccumSH_R_Sampler, uv, 0.0).x;

    // framebufIndirAccumSH_R_Prev  rgba16f
    framebufIndirAccumSH_R_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufIndirAccumSH_R_Prev[pix].x);
    v += float(framebufIndirAccumSH_R_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufIndirAccumSH_R_Prev_Sampler, uv, 0.0).x;

    // framebufIndirAccumSH_G  rgba16f
    framebufIndirAccumSH_G[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufIndirAccumSH_G[pix].x);
    v += float(framebufIndirAccumSH_G_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufIndirAccumSH_G_Sampler, uv, 0.0).x;

    // framebufIndirAccumSH_G_Prev  rgba16f
    framebufIndirAccumSH_G_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufIndirAccumSH_G_Prev[pix].x);
    v += float(framebufIndirAccumSH_G_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufIndirAccumSH_G_Prev_Sampler, uv, 0.0).x;

    // framebufIndirAccumSH_B  rgba16f
    framebufIndirAccumSH_B[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufIndirAccumSH_B[pix].x);
    v += float(framebufIndirAccumSH_B_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufIndirAccumSH_B_Sampler, uv, 0.0).x;

    // framebufIndirAccumSH_B_Prev  rgba16f
    framebufIndirAccumSH_B_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufIndirAccumSH_B_Prev[pix].x);
    v += float(framebufIndirAccumSH_B_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufIndirAccumSH_B_Prev_Sampler, uv, 0.0).x;

    // framebufIndirPingSH_R  rgba16f
    framebufIndirPingSH_R[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufIndirPingSH_R[pix].x);
    v += float(framebufIndirPingSH_R_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufIndirPingSH_R_Sampler, uv, 0.0).x;

    // framebufIndirPingSH_G  rgba16f
    framebufIndirPingSH_G[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufIndirPingSH_G[pix].x);
    v += float(framebufIndirPingSH_G_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufIndirPingSH_G_Sampler, uv, 0.0).x;

    // framebufIndirPingSH_B  rgba16f
    framebufIndirPingSH_B[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufIndirPingSH_B[pix].x);
    v += float(framebufIndirPingSH_B_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufIndirPingSH_B_Sampler, uv, 0.0).x;

    // framebufIndirPongSH_R  rgba16f
    framebufIndirPongSH_R[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufIndirPongSH_R[pix].x);
    v += float(framebufIndirPongSH_R_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufIndirPongSH_R_Sampler, uv, 0.0).x;

    // framebufIndirPongSH_G  rgba16f
    framebufIndirPongSH_G[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufIndirPongSH_G[pix].x);
    v += float(framebufIndirPongSH_G_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufIndirPongSH_G_Sampler, uv, 0.0).x;

    // framebufIndirPongSH_B  rgba16f
    framebufIndirPongSH_B[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufIndirPongSH_B[pix].x);
    v += float(framebufIndirPongSH_B_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufIndirPongSH_B_Sampler, uv, 0.0).x;

    // framebufAtrousFilteredVariance  r16f
    framebufAtrousFilteredVariance[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufAtrousFilteredVariance[pix].x);
    v += float(framebufAtrousFilteredVariance_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufAtrousFilteredVariance_Sampler, uv, 0.0).x;

    // framebufAcidFogRT  r11f_g11f_b10f
    framebufAcidFogRT[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufAcidFogRT[pix].x);
    v += float(framebufAcidFogRT_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufAcidFogRT_Sampler, uv, 0.0).x;

    // framebufAcidFog  r11f_g11f_b10f
    framebufAcidFog[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufAcidFog[pix].x);
    v += float(framebufAcidFog_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufAcidFog_Sampler, uv, 0.0).x;

    // framebufScreenEmisRT  r11f_g11f_b10f
    framebufScreenEmisRT[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufScreenEmisRT[pix].x);
    v += float(framebufScreenEmisRT_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufScreenEmisRT_Sampler, uv, 0.0).x;

    // framebufScreenEmission  r11f_g11f_b10f
    framebufScreenEmission[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufScreenEmission[pix].x);
    v += float(framebufScreenEmission_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufScreenEmission_Sampler, uv, 0.0).x;

    // framebufGodRays  r11f_g11f_b10f
    framebufGodRays[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufGodRays[pix].x);
    v += float(framebufGodRays_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufGodRays_Sampler, uv, 0.0).x;

    // framebufGodRaysFiltered  r11f_g11f_b10f
    framebufGodRaysFiltered[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufGodRaysFiltered[pix].x);
    v += float(framebufGodRaysFiltered_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufGodRaysFiltered_Sampler, uv, 0.0).x;

    // framebufBloomInput  r11f_g11f_b10f
    framebufBloomInput[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufBloomInput[pix].x);
    v += float(framebufBloomInput_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufBloomInput_Sampler, uv, 0.0).x;

    // framebufBloom_Mip1  r11f_g11f_b10f
    framebufBloom_Mip1[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufBloom_Mip1[pix].x);
    v += float(framebufBloom_Mip1_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufBloom_Mip1_Sampler, uv, 0.0).x;

    // framebufBloom_Mip2  r11f_g11f_b10f
    framebufBloom_Mip2[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufBloom_Mip2[pix].x);
    v += float(framebufBloom_Mip2_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufBloom_Mip2_Sampler, uv, 0.0).x;

    // framebufBloom_Mip3  r11f_g11f_b10f
    framebufBloom_Mip3[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufBloom_Mip3[pix].x);
    v += float(framebufBloom_Mip3_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufBloom_Mip3_Sampler, uv, 0.0).x;

    // framebufBloom_Mip4  r11f_g11f_b10f
    framebufBloom_Mip4[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufBloom_Mip4[pix].x);
    v += float(framebufBloom_Mip4_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufBloom_Mip4_Sampler, uv, 0.0).x;

    // framebufBloom_Mip5  r11f_g11f_b10f
    framebufBloom_Mip5[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufBloom_Mip5[pix].x);
    v += float(framebufBloom_Mip5_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufBloom_Mip5_Sampler, uv, 0.0).x;

    // framebufBloom_Result  r11f_g11f_b10f
    framebufBloom_Result[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufBloom_Result[pix].x);
    v += float(framebufBloom_Result_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufBloom_Result_Sampler, uv, 0.0).x;

    // framebufWipeEffectSource  r11f_g11f_b10f
    framebufWipeEffectSource[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufWipeEffectSource[pix].x);
    v += float(framebufWipeEffectSource_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufWipeEffectSource_Sampler, uv, 0.0).x;

    // framebufQ2ColorLF_SH  rgba16f
    framebufQ2ColorLF_SH[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2ColorLF_SH[pix].x);
    v += float(framebufQ2ColorLF_SH_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2ColorLF_SH_Sampler, uv, 0.0).x;

    // framebufQ2ColorLF_SH_Prev  rgba16f
    framebufQ2ColorLF_SH_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2ColorLF_SH_Prev[pix].x);
    v += float(framebufQ2ColorLF_SH_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2ColorLF_SH_Prev_Sampler, uv, 0.0).x;

    // framebufQ2ColorLF_COCG  rg16f
    framebufQ2ColorLF_COCG[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2ColorLF_COCG[pix].x);
    v += float(framebufQ2ColorLF_COCG_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2ColorLF_COCG_Sampler, uv, 0.0).x;

    // framebufQ2ColorLF_COCG_Prev  rg16f
    framebufQ2ColorLF_COCG_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2ColorLF_COCG_Prev[pix].x);
    v += float(framebufQ2ColorLF_COCG_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2ColorLF_COCG_Prev_Sampler, uv, 0.0).x;

    // framebufQ2ColorHF  r32ui
    framebufQ2ColorHF[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2ColorHF[pix].x);
    v += float(framebufQ2ColorHF_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2ColorHF_Sampler, uv, 0.0).x;

    // framebufQ2ColorHF_Prev  r32ui
    framebufQ2ColorHF_Prev[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2ColorHF_Prev[pix].x);
    v += float(framebufQ2ColorHF_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2ColorHF_Prev_Sampler, uv, 0.0).x;

    // framebufQ2ColorSpec  r32ui
    framebufQ2ColorSpec[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2ColorSpec[pix].x);
    v += float(framebufQ2ColorSpec_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2ColorSpec_Sampler, uv, 0.0).x;

    // framebufQ2ColorSpec_Prev  r32ui
    framebufQ2ColorSpec_Prev[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2ColorSpec_Prev[pix].x);
    v += float(framebufQ2ColorSpec_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2ColorSpec_Prev_Sampler, uv, 0.0).x;

    // framebufQ2ViewDepth  r32f
    framebufQ2ViewDepth[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2ViewDepth[pix].x);
    v += float(framebufQ2ViewDepth_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2ViewDepth_Sampler, uv, 0.0).x;

    // framebufQ2ViewDepth_Prev  r32f
    framebufQ2ViewDepth_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2ViewDepth_Prev[pix].x);
    v += float(framebufQ2ViewDepth_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2ViewDepth_Prev_Sampler, uv, 0.0).x;

    // framebufQ2BaseColor  rgba16f
    framebufQ2BaseColor[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2BaseColor[pix].x);
    v += float(framebufQ2BaseColor_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2BaseColor_Sampler, uv, 0.0).x;

    // framebufQ2BaseColor_Prev  rgba16f
    framebufQ2BaseColor_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2BaseColor_Prev[pix].x);
    v += float(framebufQ2BaseColor_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2BaseColor_Prev_Sampler, uv, 0.0).x;

    // framebufQ2Metallic  rg8
    framebufQ2Metallic[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2Metallic[pix].x);
    v += float(framebufQ2Metallic_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2Metallic_Sampler, uv, 0.0).x;

    // framebufQ2Metallic_Prev  rg8
    framebufQ2Metallic_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2Metallic_Prev[pix].x);
    v += float(framebufQ2Metallic_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2Metallic_Prev_Sampler, uv, 0.0).x;

    // framebufQ2BounceThroughput  rgba16f
    framebufQ2BounceThroughput[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2BounceThroughput[pix].x);
    v += float(framebufQ2BounceThroughput_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2BounceThroughput_Sampler, uv, 0.0).x;

    // framebufQ2Transparent  rgba16f
    framebufQ2Transparent[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2Transparent[pix].x);
    v += float(framebufQ2Transparent_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2Transparent_Sampler, uv, 0.0).x;

    // framebufQ2GodRaysThroughputDist  rgba16f
    framebufQ2GodRaysThroughputDist[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2GodRaysThroughputDist[pix].x);
    v += float(framebufQ2GodRaysThroughputDist_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2GodRaysThroughputDist_Sampler, uv, 0.0).x;

    // framebufQ2FogAccum  rgba16f
    framebufQ2FogAccum[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2FogAccum[pix].x);
    v += float(framebufQ2FogAccum_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2FogAccum_Sampler, uv, 0.0).x;

    // framebufQ2HistColorLF_SH  rgba16f
    framebufQ2HistColorLF_SH[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2HistColorLF_SH[pix].x);
    v += float(framebufQ2HistColorLF_SH_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2HistColorLF_SH_Sampler, uv, 0.0).x;

    // framebufQ2HistColorLF_SH_Prev  rgba16f
    framebufQ2HistColorLF_SH_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2HistColorLF_SH_Prev[pix].x);
    v += float(framebufQ2HistColorLF_SH_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2HistColorLF_SH_Prev_Sampler, uv, 0.0).x;

    // framebufQ2HistColorLF_COCG  rg16f
    framebufQ2HistColorLF_COCG[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2HistColorLF_COCG[pix].x);
    v += float(framebufQ2HistColorLF_COCG_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2HistColorLF_COCG_Sampler, uv, 0.0).x;

    // framebufQ2HistColorLF_COCG_Prev  rg16f
    framebufQ2HistColorLF_COCG_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2HistColorLF_COCG_Prev[pix].x);
    v += float(framebufQ2HistColorLF_COCG_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2HistColorLF_COCG_Prev_Sampler, uv, 0.0).x;

    // framebufQ2HistColorHF  r32ui
    framebufQ2HistColorHF[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2HistColorHF[pix].x);
    v += float(framebufQ2HistColorHF_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2HistColorHF_Sampler, uv, 0.0).x;

    // framebufQ2HistColorHF_Prev  r32ui
    framebufQ2HistColorHF_Prev[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2HistColorHF_Prev[pix].x);
    v += float(framebufQ2HistColorHF_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2HistColorHF_Prev_Sampler, uv, 0.0).x;

    // framebufQ2HistMomentsHF  rgba16f
    framebufQ2HistMomentsHF[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2HistMomentsHF[pix].x);
    v += float(framebufQ2HistMomentsHF_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2HistMomentsHF_Sampler, uv, 0.0).x;

    // framebufQ2HistMomentsHF_Prev  rgba16f
    framebufQ2HistMomentsHF_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2HistMomentsHF_Prev[pix].x);
    v += float(framebufQ2HistMomentsHF_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2HistMomentsHF_Prev_Sampler, uv, 0.0).x;

    // framebufQ2FilteredSpec  rgba16f
    framebufQ2FilteredSpec[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2FilteredSpec[pix].x);
    v += float(framebufQ2FilteredSpec_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2FilteredSpec_Sampler, uv, 0.0).x;

    // framebufQ2FilteredSpec_Prev  rgba16f
    framebufQ2FilteredSpec_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2FilteredSpec_Prev[pix].x);
    v += float(framebufQ2FilteredSpec_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2FilteredSpec_Prev_Sampler, uv, 0.0).x;

    // framebufQ2AtrousPingLF_SH  rgba16f
    framebufQ2AtrousPingLF_SH[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2AtrousPingLF_SH[pix].x);
    v += float(framebufQ2AtrousPingLF_SH_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2AtrousPingLF_SH_Sampler, uv, 0.0).x;

    // framebufQ2AtrousPongLF_SH  rgba16f
    framebufQ2AtrousPongLF_SH[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2AtrousPongLF_SH[pix].x);
    v += float(framebufQ2AtrousPongLF_SH_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2AtrousPongLF_SH_Sampler, uv, 0.0).x;

    // framebufQ2AtrousPingLF_COCG  rg16f
    framebufQ2AtrousPingLF_COCG[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2AtrousPingLF_COCG[pix].x);
    v += float(framebufQ2AtrousPingLF_COCG_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2AtrousPingLF_COCG_Sampler, uv, 0.0).x;

    // framebufQ2AtrousPongLF_COCG  rg16f
    framebufQ2AtrousPongLF_COCG[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2AtrousPongLF_COCG[pix].x);
    v += float(framebufQ2AtrousPongLF_COCG_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2AtrousPongLF_COCG_Sampler, uv, 0.0).x;

    // framebufQ2AtrousPingHF  r32ui
    framebufQ2AtrousPingHF[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2AtrousPingHF[pix].x);
    v += float(framebufQ2AtrousPingHF_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2AtrousPingHF_Sampler, uv, 0.0).x;

    // framebufQ2AtrousPongHF  r32ui
    framebufQ2AtrousPongHF[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2AtrousPongHF[pix].x);
    v += float(framebufQ2AtrousPongHF_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2AtrousPongHF_Sampler, uv, 0.0).x;

    // framebufQ2AtrousPingSpec  r32ui
    framebufQ2AtrousPingSpec[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2AtrousPingSpec[pix].x);
    v += float(framebufQ2AtrousPingSpec_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2AtrousPingSpec_Sampler, uv, 0.0).x;

    // framebufQ2AtrousPongSpec  r32ui
    framebufQ2AtrousPongSpec[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2AtrousPongSpec[pix].x);
    v += float(framebufQ2AtrousPongSpec_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2AtrousPongSpec_Sampler, uv, 0.0).x;

    // framebufQ2AtrousPingMoments  rg16f
    framebufQ2AtrousPingMoments[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2AtrousPingMoments[pix].x);
    v += float(framebufQ2AtrousPingMoments_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2AtrousPingMoments_Sampler, uv, 0.0).x;

    // framebufQ2AtrousPongMoments  rg16f
    framebufQ2AtrousPongMoments[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2AtrousPongMoments[pix].x);
    v += float(framebufQ2AtrousPongMoments_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2AtrousPongMoments_Sampler, uv, 0.0).x;

    // framebufQ2GradLFPing  rg16f
    framebufQ2GradLFPing[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2GradLFPing[pix].x);
    v += float(framebufQ2GradLFPing_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2GradLFPing_Sampler, uv, 0.0).x;

    // framebufQ2GradLFPong  rg16f
    framebufQ2GradLFPong[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2GradLFPong[pix].x);
    v += float(framebufQ2GradLFPong_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2GradLFPong_Sampler, uv, 0.0).x;

    // framebufQ2GradHFSpecPing  rg16f
    framebufQ2GradHFSpecPing[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2GradHFSpecPing[pix].x);
    v += float(framebufQ2GradHFSpecPing_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2GradHFSpecPing_Sampler, uv, 0.0).x;

    // framebufQ2GradHFSpecPong  rg16f
    framebufQ2GradHFSpecPong[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2GradHFSpecPong[pix].x);
    v += float(framebufQ2GradHFSpecPong_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2GradHFSpecPong_Sampler, uv, 0.0).x;

    // framebufQ2GradSmplPos  r32ui
    framebufQ2GradSmplPos[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2GradSmplPos[pix].x);
    v += float(framebufQ2GradSmplPos_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2GradSmplPos_Sampler, uv, 0.0).x;

    // framebufQ2GradSmplPos_Prev  r32ui
    framebufQ2GradSmplPos_Prev[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2GradSmplPos_Prev[pix].x);
    v += float(framebufQ2GradSmplPos_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2GradSmplPos_Prev_Sampler, uv, 0.0).x;

    // framebufQ2Color  rgba16f
    framebufQ2Color[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2Color[pix].x);
    v += float(framebufQ2Color_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2Color_Sampler, uv, 0.0).x;

    // framebufQ2TaaOutput  rgba16f
    framebufQ2TaaOutput[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2TaaOutput[pix].x);
    v += float(framebufQ2TaaOutput_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2TaaOutput_Sampler, uv, 0.0).x;

    // framebufQ2TaaHistory  rgba16f
    framebufQ2TaaHistory[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2TaaHistory[pix].x);
    v += float(framebufQ2TaaHistory_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2TaaHistory_Sampler, uv, 0.0).x;

    // framebufQ2TaaHistory_Prev  rgba16f
    framebufQ2TaaHistory_Prev[pix] = float4(1.0, 1.0, 1.0, 1.0);
    v += float(framebufQ2TaaHistory_Prev[pix].x);
    v += float(framebufQ2TaaHistory_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2TaaHistory_Prev_Sampler, uv, 0.0).x;

    // framebufQ2RngSeed  r32ui
    framebufQ2RngSeed[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2RngSeed[pix].x);
    v += float(framebufQ2RngSeed_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2RngSeed_Sampler, uv, 0.0).x;

    // framebufQ2RngSeed_Prev  r32ui
    framebufQ2RngSeed_Prev[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2RngSeed_Prev[pix].x);
    v += float(framebufQ2RngSeed_Prev_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2RngSeed_Prev_Sampler, uv, 0.0).x;

    // framebufQ2Cluster  r32ui
    framebufQ2Cluster[pix] = uint4(1u, 1u, 1u, 1u);
    v += float(framebufQ2Cluster[pix].x);
    v += float(framebufQ2Cluster_Sampled.Load(int3(pix, 0)).x);
    v += framebufAlbedo_Sampled.SampleLevel(framebufQ2Cluster_Sampler, uv, 0.0).x;

    probeOutput[0] = v;
}
