/*
Copyright (C) 1996-2001 Id Software, Inc.
Copyright (C) 2002-2009 John Fitzgibbons and others
Copyright (C) 2007-2008 Kristian Duske
Copyright (C) 2010-2014 QuakeSpasm developers
Copyright (C) 2016 Axel Gneiting

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

#ifndef GLQUAKE_H
#define GLQUAKE_H

#include "atomics.h"
#include "tasks.h"

void          GL_WaitForDeviceIdle (void);
qboolean      GL_BeginRendering (qboolean use_tasks, task_handle_t *begin_rendering_task, int *x, int *y, int *width, int *height);
task_handle_t GL_EndRendering (qboolean use_tasks, qboolean use_swapchain);
void          GL_SynchronizeEndRenderingTask (void);

extern int glx, gly, glwidth, glheight;

// r_local.h -- private refresh defs

#define ALIAS_BASE_SIZE_RATIO (1.0 / 11.0)
// normalizing factor so player model works out to about
//  1 pixel per triangle
#define MAX_LBM_HEIGHT        480

#define TILE_SIZE 128 // size of textures generated by R_GenTiledSurf

#define SKYSHIFT 7
#define SKYSIZE  (1 << SKYSHIFT)
#define SKYMASK  (SKYSIZE - 1)

#define BACKFACE_EPSILON 0.01

#define MAX_GLTEXTURES       4096
#define MAX_SANITY_LIGHTMAPS 256

#define NUM_COLOR_BUFFERS              2
#define INITIAL_STAGING_BUFFER_SIZE_KB 16384

#define FAN_INDEX_BUFFER_SIZE 126

#define LIGHTMAP_BYTES 4

void       R_TimeRefresh_f (void);
void       R_ReadPointFile_f (void);
texture_t *R_TextureAnimation (texture_t *base, int frame);

typedef enum
{
	pt_static,
	pt_grav,
	pt_slowgrav,
	pt_fire,
	pt_explode,
	pt_explode2,
	pt_blob,
	pt_blob2
} ptype_t;

// !!! if this is changed, it must be changed in d_ifacea.h too !!!
typedef struct particle_s
{
	// driver-usable fields
	vec3_t             org;
	float              color;
	// drivers never touch the following fields
	struct particle_s *next;
	vec3_t             vel;
	float              ramp;
	float              die;
	ptype_t            type;
} particle_t;

#define P_INVALID -1
#ifdef PSET_SCRIPT
void PScript_InitParticles (void);
void PScript_Shutdown (void);
void PScript_DrawParticles (cb_context_t *cbx);
void PScript_DrawParticles_ShowTris (cb_context_t *cbx);
struct trailstate_s;
int  PScript_ParticleTrail (vec3_t startpos, vec3_t end, int type, float timeinterval, int dlkey, vec3_t axis[3], struct trailstate_s **tsk);
int  PScript_RunParticleEffectState (vec3_t org, vec3_t dir, float count, int typenum, struct trailstate_s **tsk);
void PScript_RunParticleWeather (vec3_t minb, vec3_t maxb, vec3_t dir, float count, int colour, const char *efname);
void PScript_EmitSkyEffectTris (qmodel_t *mod, msurface_t *fa, int ptype);
int  PScript_FindParticleType (const char *fullname);
int  PScript_RunParticleEffectTypeString (vec3_t org, vec3_t dir, float count, const char *name);
int  PScript_EntParticleTrail (vec3_t oldorg, entity_t *ent, const char *name);
int  PScript_RunParticleEffect (vec3_t org, vec3_t dir, int color, int count);
void PScript_DelinkTrailstate (struct trailstate_s **tsk);
void PScript_ClearParticles (void);
void PScript_UpdateModelEffects (qmodel_t *mod);
void PScript_ClearSurfaceParticles (qmodel_t *mod); // model is being unloaded.

extern int r_trace_line_cache_counter;
#define InvalidateTraceLineCache()    \
	do                                \
	{                                 \
		++r_trace_line_cache_counter; \
	} while (0);
#else
#define PScript_RunParticleEffectState(o, d, c, t, s)   true
#define PScript_RunParticleEffectTypeString(o, d, c, n) true // just unconditionally returns an error
#define PScript_EntParticleTrail(o, e, n)               true
#define PScript_ParticleTrail(o, e, t, d, a, s)         true
#define PScript_EntParticleTrail(o, e, n)               true
#define PScript_RunParticleEffect(o, d, p, c)           true
#define PScript_RunParticleWeather(min, max, d, c, p, n)
#define PScript_ClearSurfaceParticles(m)
#define PScript_DelinkTrailstate(tsp)
#define InvalidateTraceLineCache()
#endif

#define MAX_BATCH_INDICES 65536
#define MAX_BATCH_VERTS   8196
#define NUM_WORLD_CBX     6
#define NUM_ENTITIES_CBX  6

typedef enum
{
	CBX_UPDATE_LIGHTMAPS,
	CBX_WORLD_0,
	CBX_WORLD_1,
	CBX_WORLD_2,
	CBX_WORLD_3,
	CBX_WORLD_4,
	CBX_WORLD_5,
	CBX_ENTITIES_0,
	CBX_ENTITIES_1,
	CBX_ENTITIES_2,
	CBX_ENTITIES_3,
	CBX_ENTITIES_4,
	CBX_ENTITIES_5,
	CBX_SKY_AND_WATER,
	CBX_ALPHA_ENTITIES,
	CBX_PARTICLES,
	CBX_VIEW_MODEL,
	CBX_GUI,
	CBX_POST_PROCESS,
	CBX_NUM,
} secondary_cb_contexts_t;

typedef struct cb_context_s
{
	canvastype current_canvas;
	float      cur_viewprojection[16];
	RgViewport cur_viewport;

	RgVertex *batch_verts;
	uint32_t *batch_indices;
	int       batch_verts_count;
	int       batch_indices_count;
} cb_context_t;

typedef struct
{
	// RT
	RgInstance instance;

	// Vulkan
	qboolean     validation;
	qboolean     debug_utils;
	cb_context_t primary_cb_context;
	cb_context_t secondary_cb_contexts[CBX_NUM];
	qboolean     supersampling;
	qboolean     non_solid_fill;
	qboolean     screen_effects_sops;

	// Matrices
	float projection_matrix[16];
	float view_matrix[16];
	float view_projection_matrix[16];

} vulkanglobals_t;

extern vulkanglobals_t vulkan_globals;

#define RG_CHECK(rgresult)                                                                      \
	do                                                                                          \
	{                                                                                           \
		if ((rgresult) != RG_SUCCESS)                                                           \
		{                                                                                       \
			Sys_Error ("%s. Use -condebug to write logs", rgGetResultDescription ((rgresult))); \
		}                                                                                       \
	} while (0)

//====================================================

extern int      r_visframecount; // ??? what difs?
extern int      r_framecount;
extern mplane_t frustum[4];
extern qboolean in_update_screen;
extern qboolean use_simd;

//
// view origin
//
extern vec3_t vup;
extern vec3_t vpn;
extern vec3_t vright;
extern vec3_t r_origin;

//
// screen size info
//
extern refdef_t r_refdef;
extern mleaf_t *r_viewleaf, *r_oldviewleaf;
extern int      d_lightstylevalue[256]; // 8.8 fraction of base light value

extern cvar_t r_drawentities;
extern cvar_t r_drawworld;
extern cvar_t r_drawviewmodel;
extern cvar_t r_speeds;
extern cvar_t r_pos;
extern cvar_t r_waterwarp;
extern cvar_t r_fullbright;
extern cvar_t r_lightmap;
extern cvar_t r_wateralpha;
extern cvar_t r_lavaalpha;
extern cvar_t r_telealpha;
extern cvar_t r_slimealpha;
extern cvar_t r_dynamic;

extern cvar_t gl_polyblend;
extern cvar_t gl_nocolors;

// johnfitz -- polygon offset
#define OFFSET_NONE  0
#define OFFSET_DECAL 1

// johnfitz -- rendering statistics
extern atomic_uint32_t rs_brushpolys, rs_aliaspolys, rs_skypolys, rs_particles, rs_fogpolys;
extern atomic_uint32_t rs_dynamiclightmaps, rs_brushpasses, rs_aliaspasses, rs_skypasses;

extern size_t total_device_vulkan_allocation_size;
extern size_t total_host_vulkan_allocation_size;

// johnfitz -- track developer statistics that vary every frame
extern cvar_t devstats;
typedef struct
{
	int packetsize;
	int edicts;
	int visedicts;
	int efrags;
	int tempents;
	int beams;
	int dlights;
} devstats_t;
extern devstats_t dev_stats, dev_peakstats;

// ohnfitz -- reduce overflow warning spam
typedef struct
{
	double packetsize;
	double efrags;
	double beams;
	double varstring;
} overflowtimes_t;
extern overflowtimes_t dev_overflows; // this stores the last time overflow messages were displayed, not the last time overflows occured
#define CONSOLE_RESPAM_TIME 3         // seconds between repeated warning messages

typedef struct
{
	float position[3];
	float texcoord[2];
	byte  color[4];
} basicvertex_t;

// johnfitz -- moved here from r_brush.c
extern int gl_lightmap_format;

#define LMBLOCK_WIDTH \
	1024 // FIXME: make dynamic. if we have a decent card there's no real reason not to use 4k or 16k (assuming there's no lightstyles/dynamics that need
	     // uploading...)
#define LMBLOCK_HEIGHT 1024 // Alternatively, use texture arrays, which would avoid the need to switch textures as often.

typedef struct glRect_s
{
	unsigned short l, t, w, h;
} glRect_t;
struct lightmap_s
{
	gltexture_t    *texture;
	glpoly_t       *polys;
	atomic_uint32_t modified;
	glRect_t        rectchange;

	// the lightmap texture data needs to be kept in
	// main memory so texsubimage can update properly
	byte *data; //[4*LMBLOCK_WIDTH*LMBLOCK_HEIGHT];
};
extern struct lightmap_s *lightmaps;
extern int                lightmap_count; // allocated lightmaps

extern qboolean r_fullbright_cheatsafe, r_lightmap_cheatsafe, r_drawworld_cheatsafe; // johnfitz

extern float map_wateralpha, map_lavaalpha, map_telealpha, map_slimealpha; // ericw
extern float map_fallbackalpha; // spike -- because we might want r_wateralpha to apply to teleporters while water itself wasn't watervised

extern task_handle_t prev_end_rendering_task;

// johnfitz -- fog functions called from outside gl_fog.c
void  Fog_ParseServerMessage (void);
void  Fog_FogCommand_f (void);
void  Fog_GetColor (float *c);
float Fog_GetDensity (void);
void  Fog_EnableGFog (cb_context_t *cbx);
void  Fog_DisableGFog (cb_context_t *cbx);
void  Fog_SetupFrame (cb_context_t *cbx);
void  Fog_NewMap (void);
void  Fog_Init (void);

void R_NewGame (void);

void R_AnimateLight (void);
void R_UpdateLightmaps (void *unused);
void R_MarkSurfaces (qboolean use_tasks, task_handle_t before_mark, task_handle_t *store_efrags, task_handle_t *cull_surfaces, task_handle_t *chain_surfaces);
qboolean R_CullBox (vec3_t emins, vec3_t emaxs);
void     R_StoreEfrags (efrag_t **ppefrag);
qboolean R_CullModelForEntity (entity_t *e);
void     R_RotateForEntity (float matrix[16], vec3_t origin, vec3_t angles);
void     R_MarkLights (dlight_t *light, int num, mnode_t *node);

void R_InitParticles (void);
void R_DrawParticles (cb_context_t *cbx);
void CL_RunParticles (void);
void R_ClearParticles (void);

void R_TranslatePlayerSkin (int playernum);
void R_TranslateNewPlayerSkin (int playernum); // johnfitz -- this handles cases when the actual texture changes

void R_DrawWorld (cb_context_t *cbx);
void R_DrawAliasModel (cb_context_t *cbx, entity_t *e, int entuniqueid);
void R_DrawBrushModel (cb_context_t *cbx, entity_t *e, int chain, int entuniqueid);
void R_DrawSpriteModel (cb_context_t *cbx, entity_t *e, int entuniqueid);

void R_DrawTextureChains_Water (cb_context_t *cbx, qmodel_t *model, entity_t *ent, texchain_t chain, int entuniqueid);

void GL_BuildLightmaps (void);
void GL_DeleteBModelVertexBuffer (void);
void GL_BuildBModelVertexBuffer (void);
void GL_PrepareSIMDData (void);
void GLMesh_LoadVertexBuffers (void);
void GLMesh_DeleteVertexBuffers (void);

int R_LightPoint (vec3_t p, lightcache_t *cache, vec3_t *lightcolor);
void RT_ParseElights (void);
void RT_UploadAllElights (void);
float RT_NearestStyledLightDistance (int style, const vec3_t point);
qboolean RT_AllowFakeLights (void);

void RT_ClusterLightListsReset (void);
// Registers a light for the per-cluster lists of this frame. reach is a distance in Quake units
// up to which the light belongs in a list, and it is what keeps a light of a moving entity from
// reaching every cluster of the map; zero means the light states no reach of its own, which holds
// it to nothing but the PVS row of the leaf it stands in, and no light of the renderer asks for
// that. A light that is registered twice in one frame with the same uniqueID keeps the last
// origin and reach it was given.
void RT_ClusterLightAdd (uint64_t uniqueID, const vec3_t origin, float reach);
// Reach of a light of a moving entity, from rt_light_reach_max: the distance the host promises
// such a light does not reach past. The lights of the map itself pass the reach of
// RT_ClusterLightReachStatic instead.
float RT_ClusterLightReach (void);
// Reach of a light of the map itself, from rt_light_reach: the distance such a light is heard
// from where it stands. A setting of zero falls back to the cap of RT_ClusterLightReach.
float RT_ClusterLightReachStatic (void);
void RT_ClusterLightListsUpload (void);

// Frames that reused the cached cluster light lists and frames that rebuilt them. The profiler
// reads and clears them once per reporting window, so the panel can show a hit rate.
extern int rt_cluster_cache_hits;
extern int rt_cluster_cache_misses;

// Why the cluster light lists were rebuilt, counted per rebuild. The set of registered lights
// changed; or a light moved or changed the reach it states for itself, which is what the composer
// compares (an origin it drifted more than a source quantum away from, a reach that differs, or
// the leaf it resolves into appearing or going away); or neither of the two, which is a new map,
// a new top-up reach, or a frame the incremental path turned down.
extern int rt_cluster_miss_set;
extern int rt_cluster_miss_move;
extern int rt_cluster_miss_other;

// Slots granted and refused by the last composition, reported by panel 3 of rt_stats. A non-zero
// deny count means clusters are hitting the renderer's per-list limit and dropping lights. The
// gated count is how many (light, cluster) pairs were left out for standing beyond the reach the
// light states for itself, which is what keeps a light of a moving entity from being handed to
// every list of the map.
extern int rt_cluster_last_grants;
extern int rt_cluster_last_denied;
extern int rt_cluster_last_gated;

// Lights accepted into the registry of the last frame that uploaded lists, how many additions
// were attempted by the registrars, and how many were refused by RT_CLUSTER_MAX_LIGHTS.
extern int rt_cluster_last_lights;
extern int rt_cluster_last_attempts;
extern int rt_cluster_last_dropped;
int RT_ResolvePointCluster (const vec3_t p);
void RT_BrushClusterCacheReset (void);
void RT_ClusterLightReport_f (void);
void RT_LightReport_f (void);
void RT_PrintEmissiveStats (void);
void RT_LightReportDump_f (void);
// Non-NULL while rt_light_report_dump is writing; RT_LightReportPrint mirrors every
// report line into this file in addition to the console so the dump and the readout match.
extern FILE *rt_light_report_file;
void RT_LightReportPrint (const char *fmt, ...) FUNC_PRINTF (1, 2);
void RT_WorldCensus (void);
void RT_UploadWorldLights (void);
int RT_GetSurfaceCluster (const qmodel_t *m, const msurface_t *s);

// The cluster tables of the map: the index the renderer indexes the offsets, the lists and the
// statistics with. Every leaf index that leaves the host has to go through RT_MapWorldCluster
// first, the renderer's tables being smaller than the leaf table of the shipped maps.
void RT_BuildWorldClusters (void);
void RT_FreeWorldClusters (void);
int RT_MapWorldCluster (int leaf_index);

void GL_SubdivideSurface (msurface_t *fa);
void R_BuildLightMap (msurface_t *surf, byte *dest, int stride);

void R_DrawWorld_ShowTris (cb_context_t *cbx);
void R_DrawBrushModel_ShowTris (cb_context_t *cbx, entity_t *e);
void R_DrawAliasModel_ShowTris (cb_context_t *cbx, entity_t *e);
void R_DrawParticles_ShowTris (cb_context_t *cbx);
void R_DrawSpriteModel_ShowTris (cb_context_t *cbx, entity_t *e);

void RT_UploadAllWorldModelLights (void);

void RT_ParseTeleports (void);
void RT_UploadAllTeleports (void);

#define DRAW_GL_POLY_TYPE_SKY 1
#define DRAW_GL_POLY_TYPE_SHOWTRI 2
#define DRAW_GL_POLY_TYPE_SHOWTRI_NODEPTH 3
void DrawGLPoly (cb_context_t *cbx, uint64_t uniqueid, glpoly_t *p, float color[3], float alpha, const RgTransform *transform, const gltexture_t *tex, uint32_t type);
void GL_MakeAliasModelDisplayLists (qmodel_t *m, aliashdr_t *hdr);

void Sky_Init (void);
void Sky_ClearAll (void);
void Sky_DrawSky (cb_context_t *cbx);
void Sky_NewMap (void);
void Sky_LoadTexture (qmodel_t *mod, texture_t *mt, int tex_index);
void Sky_LoadTextureQ64 (qmodel_t *mod, texture_t *mt, int tex_index);
void Sky_LoadSkyBox (const char *name);

qboolean Sky_GetBrightestPoint (float time, vec3_t dir, vec3_t color);

void R_ClearTextureChains (qmodel_t *mod, texchain_t chain);
void R_ChainSurface (msurface_t *surf, texchain_t chain);
void R_DrawTextureChains (cb_context_t *cbx, qmodel_t *model, entity_t *ent, texchain_t chain, int entuniqueid);
void R_DrawWorld_Water (cb_context_t *cbx);
void R_DrawWorld_Animated (cb_context_t *cbx);

float GL_WaterAlphaForSurface (msurface_t *fa);

static inline void R_BeginDebugUtilsLabel (cb_context_t *cbx, const char *name)
{
#ifdef _DEBUG
#endif
}

static inline void R_EndDebugUtilsLabel (cb_context_t *cbx)
{
#ifdef _DEBUG
#endif
}

static inline uint32_t RT_PackColorToUint32(uint8_t r, uint8_t g, uint8_t b, uint8_t a)
{
	return
		((uint32_t)a << 24) |
		((uint32_t)b << 16) |
		((uint32_t)g << 8)  |
		((uint32_t)r);
}
static inline uint32_t RT_PackColorToUint32_FromFloat01(float r, float g, float b, float a)
{
	return RT_PackColorToUint32 (
	    (uint8_t)CLAMP(0, r * 255.0f, 255),
	    (uint8_t)CLAMP(0, g * 255.0f, 255),
	    (uint8_t)CLAMP(0, b * 255.0f, 255),
	    (uint8_t)CLAMP(0, a * 255.0f, 255));
}

#define RT_TRANSFORM_IDENTITY { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0 }
#define RT_COLOR_WHITE { 1, 1, 1, 1 }
#define RT_PACKED_COLOR_WHITE 0xFFFFFFFF

#define RT_VEC3(x)         { (x)[0], (x)[1], (x)[2], }
#define RT_VEC3_MULT(x, a) { (x)[0] * (a), (x)[1] * (a), (x)[2] * (a), }

#define RT_VEC3_SET(dst, x, y, z) \
	do                            \
	{                             \
		(dst)[0] = (x);           \
		(dst)[1] = (y);           \
		(dst)[2] = (z);           \
	} while (0)

#define QUAKEUNIT_IN_METERS    0.025f
#define QUAKEUNIT_TO_METRIC(x) ((x)*QUAKEUNIT_IN_METERS)
#define METRIC_TO_QUAKEUNIT(x) ((x) / QUAKEUNIT_IN_METERS)

// because of units are not in meters
#define RT_QUAKE_LIGHT_AREA_INTENSITY_FIX (1.0f / (QUAKEUNIT_IN_METERS * QUAKEUNIT_IN_METERS))
// The fixup above pays for the area a lamp emits from. A sun emits from none and
// lights the whole sky, so it takes the same conversion at a fraction of it: at
// full strength rt_sun 1 overdrives the scene. The fraction is a hundredth, ten
// times below the first calibration, which read as a sun too bright for the lamps
// it shares the scene with. The god rays read this colour too, so they follow it.
// rt_sun stays the multiplier in front of it: raise it to bring daylight back.
#define RT_SUN_LIGHT_INTENSITY_SCALE 0.01f
#define RT_FIXUP_LIGHT_INTENSITY(color, witharea)                                   \
	do                                                                              \
	{                                                                               \
		extern cvar_t rt_globallight_mult;                                          \
		extern cvar_t rt_brightness;                                                \
		float         rt_light_color_[3];                                           \
		float         area = (witharea) ? RT_QUAKE_LIGHT_AREA_INTENSITY_FIX : 1.0f; \
		float         base = CVAR_TO_FLOAT (rt_globallight_mult) * area * CVAR_TO_FLOAT (rt_brightness); \
		RT_GetLightColor (rt_light_color_);                                         \
		(color)[0] *= base * rt_light_color_[0];                                    \
		(color)[1] *= base * rt_light_color_[1];                                    \
		(color)[2] *= base * rt_light_color_[2];                                    \
	} while (0)

#define RT_EMIS_LIGHT_INTENSITY_REFERENCE 0.01f
#define RT_EMIS_INTENSITY_TO_RAW(x)        ((x) * RT_EMIS_LIGHT_INTENSITY_REFERENCE)
#define RT_APPLY_LIGHT_TINT(color)         \
	do                                     \
	{                                      \
		float rt_light_color_[3];          \
		RT_GetLightColor (rt_light_color_); \
		(color)[0] *= rt_light_color_[0];  \
		(color)[1] *= rt_light_color_[1];  \
		(color)[2] *= rt_light_color_[2];  \
	} while (0)

// The colour of the sky itself (rt_sky_color) and the colour of the light the
// sky casts, as one setting.
void RT_GetSkyColor (float color[3]);
// The colour of the sun (rt_sun_color), independent of the sky: it colours the
// directional light, and with it the indirect sun, the god rays and the fog's
// sunlit shafts. The sky is not painted with it.
void RT_GetSunColor (float color[3]);
// The sun editor (rt_sun_edit): while it is on, the sun is placed where the
// crosshair points, and there it stays.
void RT_UpdateSunEditor (void);
// The colour the procedural clouds are composited over the sky with.
void RT_GetSkyCloudsColor (float color[3]);
// The tint every light source is multiplied by (see RT_FIXUP_LIGHT_INTENSITY).
void RT_GetLightColor (float color[3]);
// The colour a light starts from before its own colour and the tint are applied.
void RT_GetGlobalLightColor (float color[3]);
// The tint of a sky *texture* (rt_sky_color) as a colour filter over it. The
// procedural sky does not need it: that one is painted in rt_sky_color itself,
// and tinting it here would apply the colour to it a second time.
#define RT_APPLY_SKY_COLOR(color)        \
	do                                   \
	{                                    \
		float rt_sky_color_[3];          \
		RT_GetSkyColor (rt_sky_color_);  \
		(color)[0] *= rt_sky_color_[0];  \
		(color)[1] *= rt_sky_color_[1];  \
		(color)[2] *= rt_sky_color_[2];  \
	} while (0)
#define RT_APPLY_SUN_COLOR(color)        \
	do                                   \
	{                                    \
		float rt_sun_color_[3];          \
		RT_GetSunColor (rt_sun_color_);  \
		(color)[0] *= rt_sun_color_[0];  \
		(color)[1] *= rt_sun_color_[1];  \
		(color)[2] *= rt_sun_color_[2];  \
	} while (0)
#define RT_INIT_DEFAULT_LIGHT_COLOR(color)        \
	do                                            \
	{                                             \
		float rt_globallight_[3];                 \
		RT_GetGlobalLightColor (rt_globallight_); \
		(color)[0] = rt_globallight_[0];          \
		(color)[1] = rt_globallight_[1];          \
		(color)[2] = rt_globallight_[2];          \
	} while (0)



#define ENT_UNIQUEID_WORLD     (UINT16_MAX)
#define ENT_UNIQUEID_VIEWMODEL (UINT16_MAX + 32) 
#define RT_UNIQUEID_DONTCARE   (UINT64_MAX) 
uint64_t RT_GetBrushSurfUniqueId (int entuniqueid, const qmodel_t *model, const msurface_t *surf, uint64_t triangle /* = 0 */);
uint64_t RT_GetAliasModelUniqueId (int entuniqueid);
uint64_t RT_GetSpriteModelUniqueId (int entuniqueid);
int RT_GetEntityUniqueId (const entity_t *ent);

RgTransform RT_GetModelTransform (const float model_matrix[16]);
RgTransform RT_GetBrushModelMatrix (entity_t *e);
// Rebuilds the world's emissive light list from the current gltexture state,
// without re-uploading the world geometry (used by the qr light editor).
void      RT_RecollectWorldEmissiveLights (void);
RgFloat3D RT_AnglesToDir (/* const */ vec3_t angles);
float     RT_Luminance (const vec3_t color);

// Frame profiler for the CPU side of the render loop, enabled by panel 3 of rt_stats.
// Each slot keeps the longest duration seen in the reporting window, so tasks
// that run on several worker threads report their slowest instance instead of
// an overlapping sum.
// A slot that brackets other slots keeps a time that contains them and they must
// not be added to it: the view model task covers the model draw and the four
// uploads of the lights and the cluster lists that follow it in the same bracket.
enum
{
	RT_PROF_SETUP,
	RT_PROF_MARK,
	RT_PROF_EFRAGS,
	RT_PROF_CULL,
	RT_PROF_CHAIN,
	RT_PROF_WORLD,
	RT_PROF_SKY,
	RT_PROF_ENTS,
	RT_PROF_ALPHA,
	RT_PROF_PARTICLES,
	RT_PROF_VIEWMODEL,
	RT_PROF_VIEWMODEL_DRAW,
	RT_PROF_ELIGHTS,
	RT_PROF_WMODEL_LIGHTS,
	RT_PROF_TELEPORTS,
	RT_PROF_CLUSTERS,
	RT_PROF_CLUSTERS_LISTS,
	RT_PROF_CLUSTERS_RESOLVE,
	RT_PROF_CLUSTERS_VIS,
	RT_PROF_CLUSTERS_TOPUP,
	RT_PROF_CLUSTERS_FILL,
	RT_PROF_CLUSTERS_UPLOAD,
	RT_PROF_DRAWFRAME,
	RT_PROF_WAIT,
	RT_PROF_FRAME,

	RT_PROF_COUNT
};

// The result of the latest reporting window, drawn on screen as panel 3 of rt_stats.
typedef struct
{
	qboolean valid;
	float    fps;
	float    frameMs; // longest whole-frame time in the window
	float    waitMs;  // longest wait for the task graph
	float    ms[RT_PROF_COUNT];
	int      clusterCacheHits;   // frames of the window that reused the cached cluster light lists
	int      clusterCacheMisses; // frames that had to rebuild them
	int      clusterMissSet;     // rebuilds caused by lights appearing or disappearing
	int      clusterMissMove;    // rebuilds set off by a light that moved, changed its reach or
	                             // resolved into a different leaf
	int      clusterMissOther;   // rebuilds with neither of those, i.e. a new map, a new top-up
	                             // reach, or a frame the incremental path turned down
	int      clusterGrants;      // slots granted by the last rebuild
	int      clusterDenied;      // slots refused by the last rebuild
	int      clusterGated;       // candidate slots refused for standing beyond the light's reach
	int      clusterLights;      // lights accepted into the registry
	int      clusterAttempts;    // additions attempted by the registrars
	int      clusterDropped;     // additions refused because the registry was full
} rt_prof_report_t;

// Which readouts the rt_stats command asks for, as a bit per panel number. The
// command is the only writer, so the value can be cached for a frame at a time.
extern cvar_t rt_stats_panels;

enum
{
	RT_STATS_RAYS = 1, // ray and frame rate counters
	RT_STATS_PASSES,   // GPU frame total and per-pass timings
	RT_STATS_PROFILE,  // CPU side of the frame
};

qboolean    RT_StatsPanel (int panel);
const char *RT_ProfSlotName (int slot);

// Everything the readouts report, read in one go so that the on-screen panel and
// rt_stats_dump never disagree about which frame they are showing.
typedef struct
{
	qboolean         haveGpu;
	qboolean         haveProfile;
	unsigned int     panels;
	RgFrameStats     gpu;
	rt_prof_report_t profile;
} rt_stats_snapshot_t;

void RT_StatsCapture (rt_stats_snapshot_t *snap);

extern double           rt_prof_ms[RT_PROF_COUNT];
extern rt_prof_report_t rt_prof_report;

// Returns 0 while the profiler is off, which RT_Prof_End treats as "no sample".
double RT_Prof_Begin (void);
void   RT_Prof_End (int slot, double start);
// For slots that are measured in pieces and added up on the caller's side: the value is the
// duration of one whole pass, not of a single call.
void   RT_Prof_Sample (int slot, double ms);
void   RT_Prof_FrameStart (void);
void   RT_Prof_FrameEnd (void);
void   RT_Prof_Update (void);


#endif /* GLQUAKE_H */
