name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release, Debug]
    steps:
    - uses: actions/checkout@v4

    - name: Build QuakeRay
      run: |
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
        cmake --build build

    - name: Upload QuakeRay
      uses: actions/upload-artifact@v4
      with:
        name: QuakeRay-${{ matrix.configuration }}
        path: |
            build/quakeray.exe
            build/*.dll
